# index:
#    path: /auth
#    controller: App\Controller\MainController::index

api_login_check:
  path: /api/login_check

# books:
#     type      : rest
#     resource  : App\Controller\BookController
#     prefix    : api